version: '3.9'

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
    restart: unless-stopped
    stdin_open: true
    tty: true
